### ISSUE TITLE
Null bytes in exploit

### ISSUE THREAD

**Issue by zodiac-zodiac** [ChrisTheCoolHut/Zeratool#18]
I noticed that the majority of the exploits generated ( by Zeratool i.e. angr ) contain a null bytes in them, does this work for you ? AFAK this will break the exploit and prevent delivering the full payload if the function is expecting a null terminated input.  

 ( sorry for asking such trivial question but i was wondering how this is working with all the null bytes that we see in the generated exploits )

**Comment by ChrisTheCoolHut** [comment]
Hey @zodiac-zodiac , null bytes tend to break exploits that rely on string operations like `strcpy` and `strncpy` since they expect to terminate on that null byte. The test cases in zeratool use functions like `read` and `gets` that either terminate after n bytes or a `\n` new line character.

Zeratool is using `angr` under the hood and if a `strcpy` is present in a CTF problem, angr should present an input that doesn't have the exploit terminate early from a null byte. You may see a bunch of `\x01` instead of `\x00` which won't have the exploit terminate early.

**Comment by zodiac-zodiac** [comment]
Thank you @ChrisTheCoolHut  this is a great explanation and does solve the dilemma ! 
Thank you so much !
